// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  var BoardCtrl,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.ticTacToe = angular.module('TicTacToe', []);

  ticTacToe.constant('Settings', {
    WIN_PATTERNS: [[0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 3, 6], [1, 4, 7], [2, 5, 8], [0, 4, 8], [2, 4, 6]]
  });

  BoardCtrl = (function() {
    function BoardCtrl($scope, Settings) {
      this.$scope = $scope;
      this.Settings = Settings;
      this.mark = __bind(this.mark, this);
      this.parseBoard = __bind(this.parseBoard, this);
      this.rowStillWinnable = __bind(this.rowStillWinnable, this);
      this.fewerMoves = __bind(this.fewerMoves, this);
      this.announceWinner = __bind(this.announceWinner, this);
      this.player = __bind(this.player, this);
      this.movesRemaining = __bind(this.movesRemaining, this);
      this.numberOfMoves = __bind(this.numberOfMoves, this);
      this.resetBoard = __bind(this.resetBoard, this);
      this.getRow = __bind(this.getRow, this);
      this.getPatterns = __bind(this.getPatterns, this);
      this.$scope.cells = {};
      this.$scope.patternsToTest = this.getPatterns();
      this.$scope.mark = this.mark;
    }

    BoardCtrl.prototype.getPatterns = function() {
      return this.Settings.WIN_PATTERNS.filter(function() {
        return true;
      });
    };

    BoardCtrl.prototype.getRow = function(pattern) {
      var c, c0, c1, c2;
      c = this.$scope.cells;
      c0 = c[pattern[0]] || pattern[0];
      c1 = c[pattern[1]] || pattern[1];
      c2 = c[pattern[2]] || pattern[2];
      return "" + c0 + c1 + c2;
    };

    BoardCtrl.prototype.someoneWon = function(row) {
      return 'xxx' === row || 'ooo' === row;
    };

    BoardCtrl.prototype.resetBoard = function() {
      return this.$scope.cells = {};
    };

    BoardCtrl.prototype.numberOfMoves = function() {
      return Object.keys(this.$scope.cells).length;
    };

    BoardCtrl.prototype.movesRemaining = function(player) {
      var totalMoves;
      totalMoves = 9 - this.numberOfMoves();
      if (player === 'x') {
        return Math.ceil(totalMoves / 2);
      } else if (player === 'o') {
        return Math.floor(totalMoves / 2);
      } else {
        return totalMoves;
      }
    };

    BoardCtrl.prototype.player = function(options) {
      var moves;
      options || (options = {
        whoMovedLast: false
      });
      moves = this.numberOfMoves() - (options.whoMovedLast ? 1 : 0);
      if (moves % 2 === 0) {
        return 'x';
      } else {
        return 'o';
      }
    };

    BoardCtrl.prototype.announceWinner = function() {
      var winner;
      winner = this.player({
        whoMovedLast: true
      });
      return alert("" + winner + " wins!");
    };

    BoardCtrl.prototype.isMixedRow = function(row) {
      return !!row.match(/o+x+|x+o+/i);
    };

    BoardCtrl.prototype.hasOneX = function(row) {
      return !!row.match(/x\d\d|\dx\d|\d\dx/i);
    };

    BoardCtrl.prototype.hasTwoXs = function(row) {
      return !!row.match(/xx\d|x\dx|\dxx/i);
    };

    BoardCtrl.prototype.hasOneO = function(row) {
      return !!row.match(/o\d\d|\do\d|\d\do/i);
    };

    BoardCtrl.prototype.hasTwoOs = function(row) {
      return !!row.match(/oo\d|o\do|\doo/i);
    };

    BoardCtrl.prototype.isEmptyRow = function(row) {
      console.log("isEmptyRow?", !!row.match(/\d\d\d/i));
      return !!row.match(/\d\d\d/i);
    };

    BoardCtrl.prototype.fewerMoves = function(moves, player) {
      return this.movesRemaining(player) < moves;
    };

    BoardCtrl.prototype.rowStillWinnable = function(row) {
      console.log("moves remaining: ", this.movesRemaining());
      return this.isMixedRow(row) || (this.hasOneX(row) && this.fewerMoves(2, 'x')) || (this.hasTwoXs(row) && this.fewerMoves(1, 'x')) || (this.hasOneO(row) && this.fewerMoves(2, 'o')) || (this.hasTwoOs(row) && this.fewerMoves(1, 'o')) || (this.isEmptyRow(row) && this.movesRemaining() < 5);
    };

    BoardCtrl.prototype.parseBoard = function() {
      this.$scope.patternsToTest = this.$scope.patternsToTest.filter((function(_this) {
        return function(pattern) {
          var row;
          row = _this.getRow(pattern);
          if (_this.someoneWon(row)) {
            _this.announceWinner();
          }
          return !_this.rowStillWinnable(row);
        };
      })(this));
      return console.log(this.$scope.patternsToTest);
    };

    BoardCtrl.prototype.mark = function($event) {
      var cell;
      this.$event = $event;
      cell = this.$event.target.dataset.index;
      this.$scope.cells[cell] = this.player();
      return this.parseBoard();
    };

    return BoardCtrl;

  })();

  BoardCtrl.$inject = ["$scope", "Settings"];

  ticTacToe.controller("BoardCtrl", BoardCtrl);

}).call(this);

//# sourceMappingURL=application.map
